### ISSUE TITLE
Empty Drawer connected to External Storage crashes game

### ISSUE THREAD

**Issue by fallsimply** [refinedmods/refinedstorage2#386]
### Describe the bug

Game crashes with empty slot in Expanded Drawer while connected to RS2 External Storage

Expanded Drawer https://modrinth.com/mod/extended-drawers

### How can we reproduce this bug or crash?

1. Install Extended Drawers
2. Place a Compacting Drawer
3. Add any Ingot and a block of that same type (copper, gold, iron, etc.)
4. remove block of ingot
5. game crase

### What Minecraft version is this happening on?

Minecraft 1.19.4

### What Forge or Fabric version is this happening on?

Fabric 0.41.21

### What Refined Storage version is this happening on?

 2.0.0-milestone.2.10

### Relevant log output

```shell
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-07-07 17:09:22
Description: Ticking block entity

java.lang.IllegalArgumentException: Amount must be larger than 0
	at com.refinedmods.refinedstorage2.api.core.CoreValidations.validateLargerThanZero(CoreValidations.java:55)
	at com.refinedmods.refinedstorage2.api.resource.ResourceAmount.validate(ResourceAmount.java:70)
	at com.refinedmods.refinedstorage2.api.resource.ResourceAmount.<init>(ResourceAmount.java:23)
	at com.refinedmods.refinedstorage2.platform.fabric.internal.network.node.externalstorage.StorageExternalStorageProvider.lambda$iterator$1(StorageExternalStorageProvider.java:66)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:829)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at com.refinedmods.refinedstorage2.api.storage.external.ExternalStorage.buildCache(ExternalStorage.java:115)
	at com.refinedmods.refinedstorage2.api.storage.external.ExternalStorage.detectChanges(ExternalStorage.java:56)
	at com.refinedmods.refinedstorage2.api.network.impl.node.externalstorage.ExposedExternalStorage.detectChanges(ExposedExternalStorage.java:87)
	at com.refinedmods.refinedstorage2.api.network.impl.node.externalstorage.ExternalStorageNetworkNode.lambda$detectChanges$5(ExternalStorageNetworkNode.java:63)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at com.refinedmods.refinedstorage2.api.network.impl.node.externalstorage.ExternalStorageNetworkNode.detectChanges(ExternalStorageNetworkNode.java:63)
	at com.refinedmods.refinedstorage2.platform.common.block.entity.externalstorage.ExternalStorageBlockEntity.doWork(ExternalStorageBlockEntity.java:127)
	at com.refinedmods.refinedstorage2.platform.common.block.ticker.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:36)
	at com.refinedmods.refinedstorage2.platform.common.block.ticker.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.refinedmods.refinedstorage2.api.core.CoreValidations.validateLargerThanZero(CoreValidations.java:55)
	at com.refinedmods.refinedstorage2.api.resource.ResourceAmount.validate(ResourceAmount.java:70)
	at com.refinedmods.refinedstorage2.api.resource.ResourceAmount.<init>(ResourceAmount.java:23)
	at com.refinedmods.refinedstorage2.platform.fabric.internal.network.node.externalstorage.StorageExternalStorageProvider.lambda$iterator$1(StorageExternalStorageProvider.java:66)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:829)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at com.refinedmods.refinedstorage2.api.storage.external.ExternalStorage.buildCache(ExternalStorage.java:115)
	at com.refinedmods.refinedstorage2.api.storage.external.ExternalStorage.detectChanges(ExternalStorage.java:56)
	at com.refinedmods.refinedstorage2.api.network.impl.node.externalstorage.ExposedExternalStorage.detectChanges(ExposedExternalStorage.java:87)
	at com.refinedmods.refinedstorage2.api.network.impl.node.externalstorage.ExternalStorageNetworkNode.lambda$detectChanges$5(ExternalStorageNetworkNode.java:63)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at com.refinedmods.refinedstorage2.api.network.impl.node.externalstorage.ExternalStorageNetworkNode.detectChanges(ExternalStorageNetworkNode.java:63)
	at com.refinedmods.refinedstorage2.platform.common.block.entity.externalstorage.ExternalStorageBlockEntity.doWork(ExternalStorageBlockEntity.java:127)
	at com.refinedmods.refinedstorage2.platform.common.block.ticker.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:36)
	at com.refinedmods.refinedstorage2.platform.common.block.ticker.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: refinedstorage2:external_storage // com.refinedmods.refinedstorage2.platform.common.block.entity.externalstorage.ExternalStorageBlockEntity
	Block: Block{refinedstorage2:external_storage}[direction=up,down=true,east=false,north=false,south=false,up=false,waterlogged=false,west=false]
	Block location: World: (285,67,332), Section: (at 13,3,12 in 17,4,20; chunk contains blocks 272,-64,320 to 287,319,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{refinedstorage2:external_storage}[direction=up,down=true,east=false,north=false,south=false,up=false,waterlogged=false,west=false]
	Block location: World: (285,67,332), Section: (at 13,3,12 in 17,4,20; chunk contains blocks 272,-64,320 to 287,319,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['fallsimply'/92, l='ServerLevel[FancyGen]', x=277.40, y=68.00, z=330.38]]
	Chunk stats: 4058
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,82,32), Section: (at 0,2,0 in -3,5,2; chunk contains blocks -48,-64,32 to -33,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1078143 game time, 1102143 day time
	Level name: FancyGen
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 112491 (now: false), thunder time: 119050 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1705956024 bytes (1626 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.41.0.0
	Graphics card #1 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c03
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 61622.60
	Virtual memory used (MB): 54521.68
	Swap memory total (MB): 28921.99
	Swap memory used (MB): 4106.70
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M
	Fabric Mods: 
		adaptive-tooltips: Adaptive Tooltips 1.2.1
			com_github_llamalad7_mixinextras: mixinextras 0.2.0-beta.1
		alloy_forgery: Alloy Forgery 2.0.20+1.19.4
		amecs: Amecs 1.3.9+mc.1.19.4
			amecsapi: Amecs API 1.4.0+mc1.19.4
		appleskin: AppleSkin 2.4.4+mc1.19.4
		bagofholding: Bag Of Holding 6.0.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			extensibleenums: Extensible Enums 4.0.0
			iteminteractionscore: Item Interactions Core 6.0.0
		balm-fabric: Balm 6.0.2
		betterdeserttemples: YUNG's Better Desert Temples 1.19.4-Fabric-2.4.0
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.4-Fabric-3.4.0
		betterfortresses: YUNG's Better Nether Fortresses 1.19.4-Fabric-1.2.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.4-Fabric-3.4.0
		betterstrongholds: YUNG's Better Strongholds 1.19.4-Fabric-3.4.0
		bookshelf: Bookshelf 18.0.6
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		botanypots: BotanyPots 11.0.4
		botanytrees: BotanyTrees 7.0.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.62
		continuity: Continuity 3.0.0-beta.2+1.19.3
		convenient-mobgriefing: Convenient mobGriefing 2.1.0
		copper_pipe: Simple Copper Pipes 1.13.3
		coxinhautilities: Coxinha Utilities 1.4.8-hotpatch+1.19.4
			yet-another-config-lib: YetAnotherConfigLib 2.3.0
		diggusmaximus: Diggus Maximus 1.5.8-1.19.4
			kyrptconfig: Kyrpt Config 1.5.2-1.19.4
		doubledoors: Double Doors 5.0
		emi: EMI 1.0.5+1.19.4+fabric
		emi_loot: EMI Loot 0.6.4+1.19.4
		energizedpower: Energized Power 1.19.4-1.7.6-fabric
			team_reborn_energy: Energy 3.0.0
		expandedstorage: Expanded Storage 9.0.4
		extended_drawers: Extended Drawers 1.4.3+mc.1.19.4
			graphlib: Graph Lib 0.5.3+1.19.4
			mconfig: Mconfig 1.2.0+mc.1.19-rc1
				de_poiu_apron_apron: apron 2.1.1
				fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		extractinator: Extractinator 2.1.0
		fabric-api: Fabric API 0.85.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.27+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.28+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.37+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+0eee1254f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.30+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.9+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.47+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.57+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.13+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+10ce000ff4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.4+10ce000ff4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.48+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.16+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+10ce000ff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.55+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.20+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.9+da41e1a9f4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.18+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.31+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.35+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.4+10ce000ff4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.43+10ce000ff4
			fabric-models-v0: Fabric Models (v0) 0.3.33+10ce000ff4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.4+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.44+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.1.0+d63b52eaf4
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+86d48884f4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.11+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.3+10ce000ff4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.0+c6bbc80df4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c6bbc80df4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.41+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.31+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.24+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.44+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.4+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.6+d3afe6c3f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.48+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.23+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+c956c0e6f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.2.0+10ce000ff4
		fabric-language-kotlin: Fabric Language Kotlin 1.10.0+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		forgeconfigapiport: Forge Config API Port 6.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		forgeconfigscreens: Forge Config Screens 6.0.0
		forgero: Forgero 0.10.9+1.19.4
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			forgero-common: Forgero commons library 0.10.9+1.19.4
			forgero-compat: Forgero mod compatibility pack 0.10.9+1.19.4
			forgero-core: Forgero core 0.10.9+1.19.4
			forgero-extended: Forgero extended pack 0.10.9+1.19.4
			forgero-fabric-compat: Forgero Fabric compatibility pack 0.10.9+1.19.4
			forgero-fabric-core: Forgero Fabric core module 0.10.9+1.19.4
			forgero-structures: Forgero structure pack 0.10.9+1.19.4
			forgero-vanilla: Forgero vanilla pack 0.10.9+1.19.4
		global-datapack: Global Datapack 1.1
		inventoryessentials: Inventory Essentials 7.0.1
		inventorysorter: Inventory Sorter 1.8.10-1.19.4
		jade: Jade 10.3.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.3
		moonlight: Moonlight 1.19.4-2.4.16
		mousewheelie: Mouse Wheelie 1.11.1+mc1.19.4
			coat: Coat 1.0.0-beta.20+mc1.19.4
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.19.4
			tweed4_base: tweed4_base 1.7.1+mc1.19.4
			tweed4_data: tweed4_data 1.2.1+mc1.19.4
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.19.4
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.19.4
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.19.4
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.19.4
		mr_vanilla_refresh: Vanilla Refresh 1.4.16d
		owo: oωo 0.10.6+1.19.4
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.19.4-79-FABRIC
			fiber: fiber 0.23.0-2
		puzzleslib: Puzzles Lib 6.0.11
		refinedstorage2: Refined Storage 2 2.0.0-milestone.2.10
			com_refinedmods_refinedstorage2_refinedstorage2-query-parser_: refinedstorage2-query-parser 2.0.0-milestone.2.10
			noindium: No Indium? 1.1.0+1.19.4
			refinedstorage2-core-api: Refined Storage 2 Core API 2.0.0-milestone.2.10
			refinedstorage2-grid-api: Refined Storage 2 Grid API 2.0.0-milestone.2.10
			refinedstorage2-network: Refined Storage 2 Network 2.0.0-milestone.2.10
			refinedstorage2-network-api: Refined Storage 2 Network API 2.0.0-milestone.2.10
			refinedstorage2-resource-api: Refined Storage 2 Resource API 2.0.0-milestone.2.10
			refinedstorage2-storage-api: Refined Storage 2 Storage API 2.0.0-milestone.2.10
		reputation: Your Reputation 0.2.2+jade.1.19
		resourcefulconfig: Resourcefulconfig 1.2.0
		resourcefullib: Resourceful Lib 1.3.6
			com_teamresourceful_yabn: yabn 1.0.3
		sneaky_tree_growing: Sneaky Tree Growing 1.9.1
			me_carleslc_simple-yaml_simple-yaml: Simple-Yaml 1.7.2
			org_yaml_snakeyaml: snakeyaml 1.30
		supplementaries: Supplementaries 1.19.4-2.4.15
		tinycoal: Tiny Coal 1.1.2
		toolstats: ToolStats 14.1.5
		travelersbackpack: Traveler's Backpack 1.19.4-8.4.7
			reach-entity-attributes: Reach Entity Attributes 2.3.2
		treeharvester: Tree Harvester 8.2
		twigs: Twigs 3.0.0
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.4+1.19.4
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		yungsapi: YUNG's API 1.19.4-Fabric-3.10.1
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.19.4-Fabric-3.3.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['fallsimply'/92, l='ServerLevel[FancyGen]', x=277.40, y=68.00, z=330.38]]
	Data Packs: vanilla, Supplementaries Generated Pack, fabric, file/CommonSilicon (incompatible), file/Logsto.zip, file/OmniCut-v1.10.0+1.19.zip (incompatible), file/RottenLeather (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.4
```

**Comment by raoulvdberge** [comment]
Thanks for reporting. The mod in question is exposing a stack with a zero amount. I'm not sure if that is allowed in the API. 

Either way, I have added some checks for it.

Fixed for next release
