### ISSUE TITLE
Unable to use any blocks on fabric and forge

### ISSUE THREAD

**Issue by StarrFox** [refinedmods/refinedstorage2#408]
### Describe the bug

Currently placing what seems like any block (controller, cable, importer, exporter tested) will crash the game and if you try to load the world with it will also trigger a crash

### How can we reproduce this bug or crash?

1. place a controller

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge or Fabric version is this happening on?

forge: 47.1.43, fabric: 0.14.21

### What Refined Storage version is this happening on?

https://github.com/refinedmods/refinedstorage2/releases/tag/v2.0.0-milestone.2.12

### Relevant log output

```shell
fabric:
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2023-08-07 19:47:03
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class com.refinedmods.refinedstorage2.platform.common.block.entity.ImporterBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1937 getLevel()' of interface com.refinedmods.refinedstorage2.platform.api.network.node.PlatformNetworkNodeContainer.
	at com.refinedmods.refinedstorage2.platform.common.internal.network.LevelConnectionProvider.addInitialRequest(LevelConnectionProvider.java:69)
	at com.refinedmods.refinedstorage2.platform.common.internal.network.LevelConnectionProvider.findConnections(LevelConnectionProvider.java:47)
	at com.refinedmods.refinedstorage2.api.network.impl.NetworkBuilderImpl.initialize(NetworkBuilderImpl.java:38)
	at com.refinedmods.refinedstorage2.platform.common.PlatformApiImpl.lambda$requestNetworkNodeInitialization$5(PlatformApiImpl.java:241)
	at com.refinedmods.refinedstorage2.platform.common.util.TickHandler.runQueuedActions(TickHandler.java:16)
	at com.refinedmods.refinedstorage2.platform.fabric.ModInitializerImpl.lambda$registerTickHandler$8(ModInitializerImpl.java:302)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34)
	at net.minecraft.server.MinecraftServer.handler$zdh000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:2357)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.1.42
	Java Version: 17.0.7, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 869436416 bytes (829 MiB) / 4076863488 bytes (3888 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600X Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16974.27
	Virtual memory used (MB): 9695.95
	Swap memory total (MB): 9011.20
	Swap memory used (MB): 31.25
	JVM Flags: 2 total; -Xms512m -Xmx8096m
	Fabric Mods:
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.21
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		refinedstorage2: Refined Storage 2 2.0.0-milestone.2.12
			com_refinedmods_refinedstorage2_refinedstorage2-query-parser_: refinedstorage2-query-parser 2.0.0-milestone.2.12
			noindium: No Indium? 1.1.0+1.20
			refinedstorage2-core-api: Refined Storage 2 Core API 2.0.0-milestone.2.12
			refinedstorage2-grid-api: Refined Storage 2 Grid API 2.0.0-milestone.2.12
			refinedstorage2-network: Refined Storage 2 Network 2.0.0-milestone.2.12
			refinedstorage2-network-api: Refined Storage 2 Network API 2.0.0-milestone.2.12
			refinedstorage2-resource-api: Refined Storage 2 Resource API 2.0.0-milestone.2.12
			refinedstorage2-storage-api: Refined Storage 2 Storage API 2.0.0-milestone.2.12
			team_reborn_energy: Energy 3.0.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['AstralIneundo'/23, l='ServerLevel[test2]', x=-9.50, y=-60.00, z=0.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1




forge:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-08-07 20:04:04
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.world.level.Level com.refinedmods.refinedstorage2.platform.api.network.node.PlatformNetworkNodeContainer.m_58904_()'
	at com.refinedmods.refinedstorage2.platform.common.internal.network.LevelConnectionProvider.addInitialRequest(LevelConnectionProvider.java:69) ~[refinedstorage2-platform-forge-2.0.0-milestone.2.12.jar%23147!/:?] {re:classloading}
	at com.refinedmods.refinedstorage2.platform.common.internal.network.LevelConnectionProvider.findConnections(LevelConnectionProvider.java:47) ~[refinedstorage2-platform-forge-2.0.0-milestone.2.12.jar%23147!/:?] {re:classloading}
	at com.refinedmods.refinedstorage2.api.network.impl.NetworkBuilderImpl.initialize(NetworkBuilderImpl.java:38) ~[refinedstorage2-platform-forge-2.0.0-milestone.2.12.jar%23147!/:?] {re:classloading}
	at com.refinedmods.refinedstorage2.platform.common.PlatformApiImpl.lambda$requestNetworkNodeInitialization$5(PlatformApiImpl.java:241) ~[refinedstorage2-platform-forge-2.0.0-milestone.2.12.jar%23147!/:?] {re:classloading}
	at com.refinedmods.refinedstorage2.platform.common.util.TickHandler.runQueuedActions(TickHandler.java:16) ~[refinedstorage2-platform-forge-2.0.0-milestone.2.12.jar%23147!/:?] {re:classloading}
	at com.refinedmods.refinedstorage2.platform.forge.ModInitializer.onServerTick(ModInitializer.java:330) ~[refinedstorage2-platform-forge-2.0.0-milestone.2.12.jar%23147!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:945) ~[forge-1.20.1-47.1.43-universal.jar%23153!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:812) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.1.42
	Java Version: 17.0.7, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2660053464 bytes (2536 MiB) / 3762290688 bytes (3588 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600X Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16974.27
	Virtual memory used (MB): 9831.86
	Swap memory total (MB): 9011.20
	Swap memory used (MB): 31.00
	JVM Flags: 2 total; -Xms512m -Xmx8096m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['AstralIneundo'/1, l='ServerLevel[test]', x=-0.50, y=-60.00, z=3.50]]
	Data Packs: vanilla, mod:forge, mod:refinedstorage2
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.1.43-universal.jar                |Forge                         |forge                         |47.1.43             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		refinedstorage2-platform-forge-2.0.0-milestone.2.1|Refined Storage 2             |refinedstorage2               |2.0.0-milestone.2.12|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d65db935-e4d4-47fd-bb01-9d4c3d7aea16
	FML: 47.1
	Forge: net.minecraftforge:47.1.43
```

**Comment by raoulvdberge** [comment]
Will be fixed for the next release.
