### ISSUE TITLE
Client crashing on server while using the grid

### ISSUE THREAD

**Issue by MaciekBaginski** [refinedmods/refinedstorage2#464]
### Describe the bug

When grabbing, scrolling, viewing recipe the client crashes it happens on the server.

### How can we reproduce this bug or crash?

Couldn't find any solution

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge or Fabric version is this happening on?

0.15.3

### What Refined Storage version is this happening on?

2.0.0

### Relevant log output

```shell
[02:13:33] [Server thread/INFO]: com.refinedmods.refinedstorage2.platform.common.grid.CraftingGridContainerMenu@5aed6cb2 received a change of 538 for ItemResource[item=quartz, tag=null]
[02:13:33] [Server thread/INFO]: szymej01 lost connection: Disconnected
[02:13:33] [Server thread/INFO]: szymej01 left the game
[02:13:33] [Server thread/INFO]: Detaching com.refinedmods.refinedstorage2.api.network.impl.node.grid.GridWatcherRegistration@329ad54b from ITEM
[02:13:33] [Server thread/INFO]: Detaching com.refinedmods.refinedstorage2.api.network.impl.node.grid.GridWatcherRegistration@329ad54b from FLUID
[02:13:33] [Server thread/INFO]: Removed watcher com.refinedmods.refinedstorage2.platform.common.grid.CraftingGridContainerMenu@5aed6cb2, remaining 0
[02:13:33] [Server thread/INFO]: Finding connections for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.controller.ControllerNetworkNode@76f65780, worldPosition=class_2338{x=3576, y=59, z=4894}} with 7 existing connections
[02:13:33] [Server thread/INFO]: Processed 1 requests for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.controller.ControllerNetworkNode@76f65780, worldPosition=class_2338{x=3576, y=59, z=4894}} with 1 found entries (6 removed and 0 new)
[02:13:33] [Server thread/INFO]: Detaching 0 watchers
[02:13:33] [Server thread/INFO]: Finding connections for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.grid.GridNetworkNode@7e63874e, worldPosition=class_2338{x=3576, y=63, z=4894}} with 0 existing connections
[02:13:33] [Server thread/INFO]: Processed 1 requests for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.grid.GridNetworkNode@7e63874e, worldPosition=class_2338{x=3576, y=63, z=4894}} with 1 found entries (0 removed and 1 new)
[02:13:33] [Server thread/INFO]: Finding connections for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@6eb803f6, worldPosition=class_2338{x=3576, y=59, z=4895}} with 0 existing connections
[02:13:33] [Server thread/INFO]: Processed 1 requests for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@6eb803f6, worldPosition=class_2338{x=3576, y=59, z=4895}} with 1 found entries (0 removed and 1 new)
[02:13:33] [Server thread/INFO]: Finding connections for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@5356bd04, worldPosition=class_2338{x=3576, y=60, z=4894}} with 0 existing connections
[02:13:33] [Server thread/INFO]: Processed 1 requests for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@5356bd04, worldPosition=class_2338{x=3576, y=60, z=4894}} with 1 found entries (0 removed and 1 new)
[02:13:33] [Server thread/INFO]: Finding connections for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@6791128f, worldPosition=class_2338{x=3576, y=61, z=4894}} with 0 existing connections
[02:13:33] [Server thread/INFO]: Processed 1 requests for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@6791128f, worldPosition=class_2338{x=3576, y=61, z=4894}} with 1 found entries (0 removed and 1 new)
[02:13:33] [Server thread/INFO]: Finding connections for pivot NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.SimpleNetworkNode@532b995e, worldPosition=class_2338{x=3576, y=62, z=4894}} with 0 existing connections
```

**Comment by MaciekBaginski** [comment]
Sorry for the inconvenience here's the error log:
[00:21:58] [Netty Client IO #1/ERROR]: Encountered exception while handling in channel with name "refinedstorage2:grid_update"
java.lang.RuntimeException: null
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.updateBackingList(GridViewImpl.java:140) ~[refinedstorage2-grid-api-2.0.0-mlestone.3.2-e2c913f4d9616150.jar:?]
	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.onChange(GridViewImpl.java:120) ~[refinedstorage2-grid-api-2.0.0-mlestone.3.2-e2c913f4d9616150.jar:?]
	at com.refinedmods.refinedstorage2.platform.common.grid.AbstractGridContainerMenu.onResourceUpdate(AbstractGridContainerMenu.java:167) ~[refinedstorage2-platform-fabric-2.0.0-milestone.3.2.jar:?]
	at com.refinedmods.refinedstorage2.platform.fabric.packet.s2c.GridUpdatePacket.handle(GridUpdatePacket.java:33) ~[refinedstorage2-platform-fabric-2.0.0-milestone.3.2.jar:?]
	at com.refinedmods.refinedstorage2.platform.fabric.packet.s2c.GridUpdatePacket.lambda$receive$0(GridUpdatePacket.java:23) ~[refinedstorage2-platform-fabric-2.0.0-milestone.3.2.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.refinedmods.refinedstorage2.platform.fabric.packet.s2c.GridUpdatePacket.receive(GridUpdatePacket.java:23) ~[refinedstorage2-platform-fabric-2.0.0-milestone.3.2.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.minecraft.class_634.handler$bjc000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3268) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:21:58] [Render thread/INFO]: Minimap session finalized.
[00:21:58] [Render thread/INFO]: Finalizing world map session...
[00:21:58] [Netty Client IO #1/INFO]: [Fabric Seasons] Left dedicated server, restoring config.
