### ISSUE TITLE
Storing Crossbow Crashing Game

### ISSUE THREAD

**Issue by JustCharl** [refinedmods/refinedstorage2#716]
### Describe the bug

When attempting to put a crossbow into the storage facility, it causes the game to crash. I can't say for certain if this happens with any other items and/or tools however, I have tested this multiple times using backups and this is the only item I've found at the moment causing a crash.

I don't think it makes much of a difference but I'm using a 16k storage Disk.

---
_This is on the TNP Limitless 8 Modpack, on a Single Player World_

### How can we reproduce this bug or crash?

1. Make an RS system
2. Attempt to put a crossbow into the storage facility (I don't know if it being damaged or not is a possible contendor)

# **Item Tags**
![Screenshot 2024-11-06 135518](https://github.com/user-attachments/assets/52c468dc-b187-4716-bfc0-5912370bc324)

# **Video of steps**
https://github.com/user-attachments/assets/c1c4cbee-80c2-4df1-8023-190ca9943bfc

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

Neoforge - 21.1.74 and below

### What Refined Storage version is this happening on?

v2.0.0-milestone.4.9

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-11-06 13:55:47
Description: keyPressed event handler

java.lang.NullPointerException: keyPressed event handler


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:452) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:konkrete.mixins.json:client.IMixinScreen from mod konkrete,pl:mixin:APP:balm.neoforge.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:mixins.transmog.common.json:ScreenMixin from mod transmog,pl:mixin:APP:relics.mixins.json:ScreenMixin from mod relics,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:fancymenu.mixins.json:client.IMixinScreen from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinScreen from mod fancymenu,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.ScreenAccessor from mod refurbished_furniture,pl:mixin:APP:kubejs.mixins.json:ScreenMixin from mod kubejs,pl:mixin:APP:journeymap.mixins.json:client.ScreenAccessor from mod journeymap,pl:mixin:APP:mixins.extendedae.json:MixinScreen from mod extendedae,pl:mixin:APP:iceberg.mixins.json:ScreenMixin from mod iceberg,pl:mixin:APP:equipmentcompare.mixins.json:ScreenMixin from mod equipmentcompare,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin from mod ae2,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: com.refinedmods.refinedstorage.common.grid.screen.CraftingGridScreen
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:452) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:konkrete.mixins.json:client.IMixinScreen from mod konkrete,pl:mixin:APP:balm.neoforge.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:mixins.transmog.common.json:ScreenMixin from mod transmog,pl:mixin:APP:relics.mixins.json:ScreenMixin from mod relics,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:fancymenu.mixins.json:client.IMixinScreen from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinScreen from mod fancymenu,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.ScreenAccessor from mod refurbished_furniture,pl:mixin:APP:kubejs.mixins.json:ScreenMixin from mod kubejs,pl:mixin:APP:journeymap.mixins.json:client.ScreenAccessor from mod journeymap,pl:mixin:APP:mixins.extendedae.json:MixinScreen from mod extendedae,pl:mixin:APP:iceberg.mixins.json:ScreenMixin from mod iceberg,pl:mixin:APP:equipmentcompare.mixins.json:ScreenMixin from mod equipmentcompare,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin from mod ae2,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.keyPress(KeyboardHandler.java:407) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixins.json:client.MixinKeyboardHandler from mod konkrete,pl:mixin:APP:shulkerboxtooltip-common.mixins.json:client.KeyboardHandlerMixin from mod shulkerboxtooltip,pl:mixin:APP:mixins.sodiumextras.json:impl.borderless.KeyboardF11Mixin from mod sodiumextras,pl:mixin:APP:glitchcore.mixins.json:client.MixinKeyboardHandler from mod glitchcore,pl:mixin:APP:relics.mixins.json:KeyboardHandlerMixin from mod relics,pl:mixin:APP:kubejs.mixins.json:KeyboardHandlerMixin from mod kubejs,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$setup$8(KeyboardHandler.java:515) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixins.json:client.MixinKeyboardHandler from mod konkrete,pl:mixin:APP:shulkerboxtooltip-common.mixins.json:client.KeyboardHandlerMixin from mod shulkerboxtooltip,pl:mixin:APP:mixins.sodiumextras.json:impl.borderless.KeyboardF11Mixin from mod sodiumextras,pl:mixin:APP:glitchcore.mixins.json:client.MixinKeyboardHandler from mod glitchcore,pl:mixin:APP:relics.mixins.json:KeyboardHandlerMixin from mod relics,pl:mixin:APP:kubejs.mixins.json:KeyboardHandlerMixin from mod kubejs,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:APP:dynamic_fps-common.mixins.json:bugfix.BlockableEventLoopMixin from mod dynamic_fps,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$setup$9(KeyboardHandler.java:515) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixins.json:client.MixinKeyboardHandler from mod konkrete,pl:mixin:APP:shulkerboxtooltip-common.mixins.json:client.KeyboardHandlerMixin from mod shulkerboxtooltip,pl:mixin:APP:mixins.sodiumextras.json:impl.borderless.KeyboardF11Mixin from mod sodiumextras,pl:mixin:APP:glitchcore.mixins.json:client.MixinKeyboardHandler from mod glitchcore,pl:mixin:APP:relics.mixins.json:KeyboardHandlerMixin from mod relics,pl:mixin:APP:kubejs.mixins.json:KeyboardHandlerMixin from mod kubejs,pl:mixin:A,pl:runtimedistcleaner:A}
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.3.jar%23165!/:build 5] {}
	at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar%23177!/:build 5] {}
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar%23165!/:build 5] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:134) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.iris.json:MixinGlStateManager from mod iris,pl:mixin:APP:mixins.iris.json:MixinRenderSystem from mod iris,pl:mixin:APP:mixins.iris.json:statelisteners.MixinRenderSystem from mod iris,pl:mixin:APP:sodium-common.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:147) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.iris.json:MixinGlStateManager from mod iris,pl:mixin:APP:mixins.iris.json:MixinRenderSystem from mod iris,pl:mixin:APP:mixins.iris.json:statelisteners.MixinRenderSystem from mod iris,pl:mixin:APP:sodium-common.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.Window.updateDisplay(Window.java:290) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamic_fps-common.mixins.json:WindowMixin from mod dynamic_fps,pl:mixin:APP:sodium-common.mixins.json:core.WindowMixin from mod sodium,pl:mixin:APP:sodium-common.mixins.json:workarounds.context_creation.WindowMixin from mod sodium,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinWindow from mod immediatelyfast,pl:mixin:APP:sodium-extra.mixins.json:adaptive_sync.MixinWindow from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:reduce_resolution_on_mac.MixinWindow from mod sodium_extra,pl:mixin:APP:mixins.sodiumextras.json:impl.borderless.BorderlessWindowMixin from mod sodiumextras,pl:mixin:APP:mixins.sodiumextras.json:impl.borderless.accessors.MainWindowAccessor from mod sodiumextras,pl:mixin:APP:relics.mixins.json:WindowMixin from mod relics,pl:mixin:APP:kubejs.mixins.json:WindowMixin from mod kubejs,pl:mixin:APP:mixins.iris.json:MixinWindow from mod iris,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1217) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin from mod hammerlib,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod iris,pl:mixin:APP:omega-config.mixins.json:ClientMixin from mod omegaconfig,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin from mod dynamic_fps,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:sodium-common.mixins.json:core.MinecraftMixin from mod sodium,pl:mixin:APP:sodium-neoforge.mixins.json:platform.neoforge.EntrypointMixin from mod sodium,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:globalpacks.mixins.json:MinecraftMixin from mod globalpacks,pl:mixin:APP:glassential.mixins.json:MixinMinecraft from mod glassential,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:bookshelf.mixins.json:access.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient from mod inventoryprofilesnext,pl:mixin:APP:monolib.mixins.json:MinecraftMixin from mod monolib,pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium_extra,pl:mixin:APP:mixins.sodiumextras.json:impl.fps.GpuUsageMixin from mod sodiumextras,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:mekanismcovers.mixins.json:MinecraftMixin from mod mekanismcovers,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin from mod fallingleaves,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod glitchcore,pl:mixin:APP:mod_menu.mixins.json:MixinMinecraft from mod mod_menu,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:attributesfix.mixins.json:MixinMinecraft from mod attributesfix,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:bankstorage.client.mixins.json:ItemPickMixin from mod bankstorage,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftClientMixin from mod betterthirdperson,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod journeymap,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod moonlight,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:forbidden_arcanus.mixins.json:client.MinecraftMixin from mod forbidden_arcanus,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin from mod hammerlib,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod iris,pl:mixin:APP:omega-config.mixins.json:ClientMixin from mod omegaconfig,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin from mod dynamic_fps,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:sodium-common.mixins.json:core.MinecraftMixin from mod sodium,pl:mixin:APP:sodium-neoforge.mixins.json:platform.neoforge.EntrypointMixin from mod sodium,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:globalpacks.mixins.json:MinecraftMixin from mod globalpacks,pl:mixin:APP:glassential.mixins.json:MixinMinecraft from mod glassential,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:bookshelf.mixins.json:access.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient from mod inventoryprofilesnext,pl:mixin:APP:monolib.mixins.json:MinecraftMixin from mod monolib,pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium_extra,pl:mixin:APP:mixins.sodiumextras.json:impl.fps.GpuUsageMixin from mod sodiumextras,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:mekanismcovers.mixins.json:MinecraftMixin from mod mekanismcovers,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin from mod fallingleaves,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod glitchcore,pl:mixin:APP:mod_menu.mixins.json:MixinMinecraft from mod mod_menu,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:attributesfix.mixins.json:MixinMinecraft from mod attributesfix,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:bankstorage.client.mixins.json:ItemPickMixin from mod bankstorage,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftClientMixin from mod betterthirdperson,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod journeymap,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod moonlight,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:forbidden_arcanus.mixins.json:client.MinecraftMixin from mod forbidden_arcanus,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23664!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:screenshotclipboard-common.mixins.json:AWTHackMixin from mod screenshotclipboard,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23112!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23112!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23112!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23112!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23125!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23125!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23125!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23125!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23125!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23125!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23125!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
```

**Comment by raoulvdberge** [comment]
Did you include the full crash report?

**Comment by JustCharl** [comment]
That was the most recent once that I had from testing. I have other ones from previous crashes if you'd like them.

**Comment by raoulvdberge** [comment]
Hello, thanks for reporting this. This seems to be an issue in PickleTweaks. I've reported it in https://github.com/BlakeBr0/PickleTweaks/issues/96 but also added more protection on the RS-side so it doesn't crash anymore.
